<?php
SELECT F_1CUO_SDP,CODPRE_SDP FROM SGCAF310 WHERE CODPRE_SDP='023' GROUP BY F_1CUO_SDP,CODPRE_SDP ORDER BY F_1CUO_SDP 
SELECT F_1CUO_SDP,CODPRE_SDP FROM SGCAF310 WHERE CODPRE_SDP='053' GROUP BY F_1CUO_SDP,CODPRE_SDP ORDER BY F_1CUO_SDP 
SELECT F_1CUO_SDP,CODPRE_SDP FROM SGCAF310 WHERE CODPRE_SDP='057' GROUP BY F_1CUO_SDP,CODPRE_SDP ORDER BY F_1CUO_SDP 
SELECT F_1CUO_SDP,CODPRE_SDP FROM SGCAF310 WHERE CODPRE_SDP='058' GROUP BY F_1CUO_SDP,CODPRE_SDP ORDER BY F_1CUO_SDP 
?>
